export const BUTTON_TEXT = {
  CREATE_JSON: 'Create JSON',
  CREATE_XLSX: 'Create XLSX',
  COPY_TO_CLIPBOARD: 'Copy to clipboard',
  SCAN_FOR_ASINS: 'Scan for ASINs',
  UPLOAD_TO_WAIVIO: 'Upload to Waivio',
  CREATE_POST_DRAFT: 'Post draft',
  CREATE_RECIPE_DRAFT: 'Recipe draft',
  TUTORIAL_DRAFT: 'Tutorial draft',
  GET_GOOGLE_ID: 'Show Google ID',
  GET_OSM_ID: 'Show OSM ID',
  CREATE_LINK: 'Create exact link',
  CREATE_LINK_ALL: 'Link object',
  CREATE_POST: 'Re-post',
  EDIT_WITH_AI: 'Analyze with AI',
};
