export const EXTERNAL_URL = {
  WAIVIO_IMPORT: 'https://www.waivio.com/import-objects-service/import-products',
  HIVE_SIGNER_ME: 'https://hivesigner.com/api/me',
  WAIVIO_IMPORT_NOT_PUBLISHED: 'https://www.waivio.com/import-objects-service/asins-not-published',
  WAIVIO_IMPORT_GPT_QUERY: 'https://www.waivio.com/import-objects-service/gpt-query',
  WAIVIO_IMPORT_VIDEO_ANALYSES: 'https://www.waivio.com/import-objects-service/video-analyses',
  WAIVIO_IMAGE: 'https://www.waivio.com/api/image',
  WAIVIO_PERMLINK_BY_ID: 'https://www.waivio.com/api/wobjects/id-type',
  WAIVIO_PERMLINK_BY_FIELD_BODY: 'https://www.waivio.com/api/wobjects/field-body',
  WAIVIO_POST_IMPORT_HOST: 'https://www.waivio.com/import-objects-service/post-import/host',
  WAIVIO_POST_IMPORT: 'https://www.waivio.com/import-objects-service/post-import',
  WAIVIO_IMPORT_VALIDATE: 'https://www.waivio.com/import-objects-service/import-products/validate',
  WAIVIO_GENERATE_RECIPE: 'https://www.waivio.com/import-objects-service/import-products/recipe-generation',
  WAIVIO_EXTRACT_ID: 'https://www.waivio.com/import-objects-service/import-products/extract-id',
  WAIVIO_GENERATE_PRODUCT: 'https://www.waivio.com/import-objects-service/product-image-analyses',
  WAIVIO_CREATE_OBJECT: 'https://www.waivio.com/objects-bot/create-object',
  WAIVIO_CREATE_UPDATE: 'https://www.waivio.com/objects-bot/append-object',
};
